version: '3.7'

services:

  tor_servers:
    image: tors_image:latest
    build:
      context: tors/
      dockerfile: Dockerfile
    environment:
      - TOR_INSTANCES=30
      - TOR_PORT_BASE=9000
    ports:
      - 9001-9030:9001-9030

  proxy_tor:
    build:
      context: src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_Logging__LogLevel__Default=Debug
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_Port=5008
      - ASPNETCORE_Tor__hostname=tor_servers
      - ASPNETCORE_Tor__portFrom=9001
      - ASPNETCORE_Tor__portTo=9030
    depends_on:
      - tor_servers
    ports:
      - 5008:5008
