version: '3.7'

services:

  tor:
    container_name: tors
    build:
      context: tors/
      dockerfile: Dockerfile
    environment:
      - TOR_INSTANCES=30
    image: tors_image:latest
    ports:
      - 9000-9029:9000-9029

  proxy:
    build:
      context: src/
      dockerfile: Dockerfile
    environment:
      - ASPNETCORE_Logging__LogLevel__Default=Debug
      - ASPNETCORE_ENVIRONMENT=Development
    depends_on:
      - tor
    ports:
      - 5005:5005

  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - proxy
      - tor
    command: proxy:5005