FROM alpine:latest
RUN apk update && apk upgrade && \
    apk add tor curl bash && \
    rm /var/cache/apk/* && \
    cp /etc/tor/torrc.sample /etc/tor/torrc && \
    echo $'StrictNodes 1 \n\
AllowSingleHopCircuits 1 \n\
FastFirstHopPK 0 \n\
EnforceDistinctSubnets 0 \n\
UseEntryGuards 0 \n\
' > torrc

ADD start.sh /usr/local/bin/start.sh
RUN chmod +x /usr/local/bin/start.sh

RUN echo | sed -i 's/\r$//' /usr/local/bin/start.sh

CMD /usr/local/bin/start.sh
